id: P000049
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །རྡོ་རྗེའི་གསང་བའི་སྔགས་ཀྱི་རྒྱལ་པོ་བཛྲ་གུ་རུའི་དགོངས་དོན་རྣམ་པར་བཤད་པ་ཟབ་དོན་རྡོ་རྗེའི་གསང་མཛོད་ལས་ཅན་དད་བརྒྱའི་དགའ་སྟོན་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  - quotation
  - yigchung
  id: SHE-DKR-08
web_metadata:
  title:
    en: A Celebration of Great Karmic Devotion:The Profound Meaning of the Secret
      Vajra Treasury, A Commentary on the Meaning of Vajra Guru, the King of Secret
      Mantra
    bo: རྡོ་རྗེའི་གསང་བའི་སྔགས་ཀྱི་རྒྱལ་པོ་བཛྲ་གུ་རུའི་དགོངས་དོན་རྣམ་པར་བཤད་པ་ཟབ་དོན་རྡོ་རྗེའི་གསང་མཛོད་ལས་ཅན་དད་བརྒྱའི་དགའ་སྟོན་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 8
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༨
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-08
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-08.epub
  description:
    en: ''
    bo: ''
